FRONTENDSCHOOL5/final-18-EarthUs

- src/pages/SignIn.jsx
[✨ feat:  전역 상태 관리를 위한 로그인 기능 초안 구현](https://github.com/FRONTENDSCHOOL5/final-18-EarthUs/commit/5297450f0048510452fcf32162a68700ce937b6c)
- initialUserData에 로컬스토리지에 저장된 유저 데이터를 표시해서 로그인 상태 유지.
- mount시 로컬스토리지에 데이터가 있으면 userData에 저장.
- recoil을 사용해서 userDataAtom 변경
- Email, Password 입력시 state 변경하는 Handler 함수 실행
- 로그인 버튼 클릭시 비동기 통신 실행 
- 로그아웃 버튼 클릭시 로컬스토리지, 리코일 데이터 삭제
➕ [src/pages/ClubUpload/ClubUpload.jsx
](https://github.com/FRONTENDSCHOOL5/final-18-EarthUs/commit/5297450f0048510452fcf32162a68700ce937b6c)
> 로그인 페이지 기능 구현

- src/components/common/button/Button.jsx
[✨ feat: 버튼 컴포넌트 구현](https://github.com/FRONTENDSCHOOL5/final-18-EarthUs/commit/73b98f2284abab5ab06ae527d979eaa907cce59b)
- 사이즈별 버튼 구현
- 색상별 버튼 구현
-  아이콘이 있는 경우 예외처리
- cta버튼은 position:fixed 예외처리
- disabled 예외처리
➕ src/components/common/button/Button.jsx
- #4
> 버튼 컴포넌트 구현

- src/components/common/a11yHidden/A11yHidden.jsx
- src/components/common/a11yHidden/a11yHidden.style.js
[✨ feat: 스크린 아웃 컴포넌트 구현
](https://github.com/FRONTENDSCHOOL5/final-18-EarthUs/commit/fa01f05faa08103b844d6230b6a29d59c55d90df)
- 컴포넌트 내부 컨텐츠는 `{children}`을 사용해서 동적으로 제어
- 마크업은 `span`태그로 정의
➕ src/components/common/a11yHidden/A11yHidden.jsx
➕ src/components/common/a11yHidden/a11yHidden.style.js
- #8
> ✨ feat: 스크린 아웃 컴포넌트 구현

- src/components/common/header/Header.jsx
- src/components/common/header/header.style.jsx
> ✨ feat: 헤더 컴포넌트 구현

- src/components/common/tabBar/TabBar.jsx
- src/components/common/tabBar/tabBar.style.js
- src/routes/Router.jsx
> ✨ feat: 헤더, 탭바 라우터 설정

- src/components/common/header/Header.jsx
- src/routes/Router.jsx
- 라우터 변경
- 헤더, 헤더프로필 나누어져있던 컴포넌트 헤더 하나로 통합
> 🦄 refactor: 라우터 변경 및 헤더 컴포넌트 수정

- src/components/common/button/Button.jsx
- 버튼 폰트사이즈 적용 누락건 수정
- 가상요소 SIZES 변수에도 VARIANTS CSS 우선순위 영향을 받아 가상요소에 filter 적용되는 이슈 발생해서 순서 변경
- #4
> 🌈 style: 버튼 컴포넌트 CSS 수정

- src/components/common/avatar/Avatar.jsx
- src/components/common/avatar/avatar.style.js
> ✨ feat: 아바타 공통 컴포넌트 구현

- src/components/common/input/Input.jsx
- required 값 조건부 렌더링으로 변경
- #2
> ✨ feat: required 값 조건부 렌더링으로 변경

- src/components/common/card/Card.jsx
- src/components/common/card/card.style.js
> ✨ feat: Card 컴포넌트 구현

- src/components/common/input/Input.jsx
- src/components/common/input/InputError.jsx
- src/components/common/input/input.style.js
- input 값 추가 시, `유효 상태 및 포커스 상태`에 변경되던 border-bottom-color를 `값이 입력되거나 포커스 상태일 때`로 변경
- 변경 style 관련 주석 추가
- #2
> 🌈 style: border-bottom-color 설정 변경

- src/components/common/comment/Comment.jsx
- src/components/common/comment/comment.style.js
- props 전달
- 댓글 작성 시간 출력
- #37
> ✨ feat: 댓글 컴포넌트 구현

- src/components/blank/Blank.jsx
- src/components/blank/blank.style.js
- 팔로잉 없을 때 보이는 컴포넌트
- ‘유저 검색하기’ 버튼 라우터 설정
- #29
> ✨ feat: Blank 컴포넌트 구현

- src/components/common/input/input.style.js
- src/pages/profile/profileUpload/ProfileUpload.jsx
- 이미지 업로드 기능 추가
- input width 값 수정
- #58
> ✨ feat, 🌈 style : 프로필 기능 추가 및 input 스타일 수정

- src/pages/follow/Follow.jsx
- src/pages/follow/follow.style.js
- following/followers 페이지 라우터 사용해서 조건부 렌더링
- 팔로우/언팔로우 기능
- #34
> ✨ feat: 팔로우 페이지 구현

- src/components/common/modal/Modal.jsx
- src/components/common/modal/modal.style.js
- src/recoil/modalConfigAtom.js
- src/recoil/modalStateAtom.js
- Confirm 모달
- Bottom-sheet 모달
- 리코일로 모달 전역상태 관리
- #6
> ✨ feat: 모달 공통 컴포넌트 추가

- src/components/blank/Blank.jsx
- src/components/blank/blank.style.js
- src/components/common/header/Header.jsx
- src/components/common/tabBar/TabBar.jsx
- src/components/userInfo/UserInfo.jsx
- src/components/userInfo/userInfo.style.js
- 모달 핸들러 함수 연결 추가
- 내 프로필 인식할 수 있게 조건식 추가
- props로 동적 데이터 관리 추가
> ✨ 기존 컴포넌트 동적으로 리팩토링

- src/pages/home/Home.jsx
- src/routes/Router.jsx
> ✨ feat: 라우터 초기 설정

- src/components/common/card/Card.jsx
- src/components/common/card/card.style.js
- 이미지 여러장인 경우 Swiper 라이브러리 조건식 추가
- userInfo에 전달해 줄 onClick 이벤트 props 파라미터 추가
- 상품에도 사용할 수 있도록 조건부 렌더링 추가
- #30
> ✨ feat: Swiper 및 클릭이벤트 조건별 랜더링 추가

- src/components/profileFeed/ProfileFeed.jsx
- src/components/profileFeed/profileFeed.style.js
- src/components/profileHeader/ProfileHeader.jsx
- src/components/profileHeader/profileHeader.style.js
- src/components/profileProduct/ProfileProduct.jsx
- src/components/profileProduct/profileProduct.style.js
- src/pages/product/productDetail/ProductDetail.jsx
- src/pages/product/productDetail/productDetail.style.js
- src/pages/profile/profileDetail/ProfileDetail.jsx
- 사용자 정보 표시
- 사용자 판매 상품 표시
- 사용자 피드 게시물 표시
- 내 프로필 조건부 렌더링
- #1 
- #15
- #17   
- #18 
- #19 
- #20 
- #52
> ✨ feat: 프로필 페이지 구현

- src/components/chatBubble/ChatBubble.jsx
- src/components/chatBubble/chatBubble.style.js
- src/pages/chat/chatRoom/ChatRoom.jsx
- src/pages/chat/chatRoom/chatRoom.style.js
- src/routes/Router.jsx
- 채팅방 페이지 구현 (마크업, 스타일링)
- 채팅방 메시지 컴포넌트 구현 (마크업, 스타일링)
- 채팅 목록 클릭 시 채팅방으로 이동
- 이미지 선택 시 전송 버튼 활성화
- 수신 및 발신에 따른 메시지 컴포넌트 조건부 렌더링
- 메시지 실제 전송 시간 표시
- 입력 버튼 클릭 시, 텍스트 및 이미지 채팅창 출력
- Enter 시, 메시지 전송되도록 키보드 이벤트 구현
- Input이 비어있을 시, onKeyPress 및 onClick 이벤트 비활성화
- #16
- #56
- #66
- #67
> ✨ feat, 🌈 style: 채팅 메시지 컴포넌트 및 채팅방 페이지 구현

- src/pages/product/productUpload/ProductUpload.jsx
- src/pages/product/productUpload/productUpload.style.js
- src/routes/Router.jsx
- input 유효성 검사 + 에러 메세지
- 이미지 파일크기, 확장자명 검사
- 상품 등록/수정 기능
- 라우터 사용해서 조건부 api 호출
- input 모두 유효하게 입력 시 '저장' 버튼 활성화
- #26 
- #27 
- #28
> ✨ feat: productUpload 페이지 구현

- src/components/common/comment/Comment.jsx
- 삭제, 신고 기능 : useApiMutation 커스텀 훅 호출
- 바텀시트, 모달 조건부 렌더링 : 댓글 작성자 로그인한 유저와 동일하면 삭제, 동일하지 않으면 신고 
- #37
> ✨ feat: 댓글 컴포넌트 삭제/신고 모달 및 기능 구현

- src/pages/follow/Follow.jsx
> ✨ feat: 팔로우 알림관리 모달 구현

- src/components/chatPreview/ChatPreview.jsx
- src/components/chatPreview/chatPreview.style.js
- src/pages/chat/chatList/ChatList.jsx
- src/routes/Router.jsx
- 채팅 목록 마크업 (구조, 스타일)
- 필수 기능: 읽지 않은 메시지가 있는 채팅방은 프로필 상단 좌측에 작은 원 표시
- #13
> ✨ feat: 채팅 목록 페이지 구현

- src/components/userInfo/UserInfo.jsx
- src/components/userInfo/userInfo.style.js
- src/pages/search/Search.jsx
- 유저 검색 API 호출
- 팔로우, 언팔로우 API 호출
- 선택 기능: 검색어와 일치하는 단어 파란색으로 표시
- #10
- #12
[ ]  UserInfo에 Search 하이라이트 기능 관련으로 변경사항이 있습니다!
> ✨ feat: Search 페이지 구현

- src/components/common/header/Header.jsx
- src/components/userInfo/userInfo.style.js
- src/routes/Router.jsx
- SearchInput과 검색 페이지 연동
- 검색 페이지 경로 추가
- #74
> ✨ feat: SearchInput과 검색 페이지 연동

- src/pages/profile/profileUpload/ProfileUpload.jsx
- src/pages/profile/profileUpload/ProfileUpload.style.js
- 키보드 이벤트 추가
- 프로필 사진 영역 style 수정 (불필요한 margin 삭제, 레이아웃 배치 수정)
- 프로필 정보 불러오기 API로 수정 전 데이터 받아오기
- #7
- #9
> ✨ feat: 프로필 정보 불러오는 기능 추가

- src/components/common/header/Header.jsx
- 검색 이벤트 핸들러 추가
- Input type 값 변경
- #74
> ✨ feat: 검색 이벤트 추가

- src/components/userInfo/UserInfo.jsx
- src/components/userInfo/userInfo.style.js
- 검색 페이지 UserInfo margin 추가
- #74
> 🌈 style: 검색 페이지 UserInfo margin 추가

- src/pages/post/postDetail/PostDetail.jsx
- src/pages/post/postDetail/postDetail.style.js
- 댓글 인풋에 프로필 사진(avatar 컴포넌트) 출력
- 댓글 인풋 입력 시 ‘입력’ 버튼 활성화
- 게시글, 댓글 : useApiQuery 커스텀훅으로 api 호출
- 댓글 작성 : useApiMutation 커스텀훅으로 api 호출
- 댓글 작성시 맨 밑으로 스크롤
- #36
> ✨ feat: postDetail 페이지 구현

- src/pages/chat/chatRoom/ChatRoom.jsx
- deprecated 이슈로 인해 onKeyPress 이벤트를 onKeyDown으로 변경
- 메시지 중복 키 오류 수정
- 웹 접근성을 위해 aria-label 추가
- #67
> 🐞 fix: keyDown 이벤트, 메시지 중복 키 오류 수정

- src/hooks/useApiInfiniteQuery.jsx
- src/pages/feed/Feed.jsx
- src/pages/post/postDetail/PostDetail.jsx
- useInfiniteQuery 실행하는 커스텀 훅 생성 `useApiInfiniteQuery.jsx`
- 피드페이지 게시글, 댓글 무한 스크롤
- `react-infinite-scroller` 라이브러리 사용
- #32
> ✨ feat: 무한 스크롤 기능 구현

- src/pages/product/productUpload/ProductUpload.jsx
- src/pages/product/productUpload/productUpload.style.js
- useState 규격화
- 함수명 작성할 필요가 없도록 `validationFields` 핸들러 함수에 switch 조건식으로 유효성 검사 
- Input 컴포넌트에 props 보내는 형식 수정
- 에러메시지 자동 출력되도록 수정
- 버튼 조건식 추가
- #86
> 🦄 refactor: 상품 등록 입력필드 규격화

- src/pages/product/productUpload/ProductUpload.jsx
- src/pages/product/productUpload/productUpload.style.js
- src/pages/profile/profileUpload/ProfileUpload.jsx
- useState 규격화
- 함수명 작성할 필요가 없도록 `validationFields` 핸들러 함수에 switch 조건식으로 유효성 검사 
- Input 컴포넌트에 props 보내는 형식 수정
- 에러메시지 자동 출력되도록 수정
- 버튼 조건식 추가
- #86
> 🦄 refactor: 프로필 등록 입력필드 규격화

- src/hooks/useValidations.jsx
- src/pages/profile/profileEdit/ProfileEdit.jsx
- src/pages/profile/profileEdit/ProfileEditForm.jsx
- src/pages/profile/profileUpload/ProfileImageField.jsx
- src/pages/profile/profileUpload/ProfileTitle.jsx
- src/pages/profile/profileUpload/ProfileUpload.jsx
- src/pages/profile/profileUpload/ProfileUpload.style.js
- src/pages/sign/SignUp.jsx
- src/routes/Router.jsx
- 회원가입 입력폼별 순차처리 구현
- 인풋필드 유효성 검사 모듈패턴 적용해서 커스텀 훅 제작
- 프로필 업로드, 프로필 수정 페이지 분리
- 컴포넌트 신규 제작
- 프로필 타이틀
- 이미지 업로드
- 인풋필드 업로드 
- #98
> ✨ feat: 회원가입 기능 구현

- src/components/common/modal/Modal.jsx
- 모달이 열렸을 때, 모달 형태가 달라질 때 버튼 개수에 따라 모달 안에서만 포커스 이동하기
- #100
> ✨ feat: 모달 팝업 접근성 향상

- src/components/common/modal/modal.style.js
- src/components/common/tabBar/TabBar.jsx
- src/components/userInfo/userInfo.style.js
- src/hooks/useScrollTop.jsx
- src/styles/GlobalStyle.jsx
- 탭바 클릭시 화면 최상단으로 이동
- 모바일 기기 대응 및 크로스브라우징을 위한 전역 스타일 수정
> ✨ feat: 스크롤 커스텀훅 추가

- src/components/View/ColumnView.jsx
- src/components/View/GridView.jsx
- src/components/View/View.style.js
- src/components/profileFeed/ProfileFeed.jsx
- src/components/profileFeed/profileFeed.style.js
- Column 컴포넌트 생성
- Grid 컴포넌트 생성
- #105
> 🦄 refactor: 프로필 피드보기 컴포넌트 분리
